create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 1 and 50),
  phone_last4 text not null check (phone_last4 ~ '^[0-9]{4}$'),
  rank text not null default '10급',
  tier text not null default '준회원',
  current_status text not null default '오프라인'
    check (current_status in ('오프라인', '출석중', '대국중')),
  last_check_in timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_phone_last4_name_key
  on public.profiles (phone_last4, name);

create index if not exists profiles_status_check_in_idx
  on public.profiles (current_status, last_check_in desc);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default '출석중'
    check (status in ('출석중', '귀가')),
  checked_in_at timestamptz not null default now(),
  checked_out_at timestamptz,
  constraint attendance_checkout_order check (
    checked_out_at is null or checked_out_at >= checked_in_at
  )
);

create index if not exists attendance_user_checked_in_idx
  on public.attendance (user_id, checked_in_at desc);

create index if not exists attendance_open_sessions_idx
  on public.attendance (user_id, checked_in_at desc)
  where checked_out_at is null;

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_type text not null default '친선전',
  black_team uuid[] not null default '{}',
  white_team uuid[] not null default '{}',
  handicap text not null default '호선(덤 6.5집)',
  phase text not null default '진행중'
    check (phase in ('진행중', '종료', '취소')),
  winner text
    check (winner is null or winner in ('흑승', '백승', '무승부', '취소')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  constraint matches_non_empty_teams check (
    cardinality(black_team) > 0 and cardinality(white_team) > 0
  ),
  constraint matches_end_state check (
    (phase = '진행중' and ended_at is null and winner is null)
    or (phase = '취소' and ended_at is not null and winner = '취소')
    or (phase = '종료' and ended_at is not null and winner in ('흑승', '백승', '무승부'))
  )
);

create index if not exists matches_phase_started_at_idx
  on public.matches (phase, started_at desc);

create or replace function public.set_match_ended_at()
returns trigger
language plpgsql
as $$
begin
  if new.phase in ('종료', '취소') and new.ended_at is null then
    new.ended_at := now();
  elsif new.phase = '진행중' then
    new.ended_at := null;
    new.winner := null;
  end if;
  return new;
end;
$$;

drop trigger if exists matches_set_ended_at on public.matches;
create trigger matches_set_ended_at
before insert or update of phase, winner, ended_at on public.matches
for each row execute function public.set_match_ended_at();

alter table public.profiles enable row level security;
alter table public.attendance enable row level security;
alter table public.matches enable row level security;

drop policy if exists "Public kiosk can read profiles" on public.profiles;
create policy "Public kiosk can read profiles"
on public.profiles for select to anon, authenticated using (true);

drop policy if exists "Public kiosk can register profiles" on public.profiles;
create policy "Public kiosk can register profiles"
on public.profiles for insert to anon, authenticated with check (true);

drop policy if exists "Public kiosk can update profiles" on public.profiles;
create policy "Public kiosk can update profiles"
on public.profiles for update to anon, authenticated using (true) with check (true);

drop policy if exists "Public kiosk can read attendance" on public.attendance;
create policy "Public kiosk can read attendance"
on public.attendance for select to anon, authenticated using (true);

drop policy if exists "Public kiosk can create attendance" on public.attendance;
create policy "Public kiosk can create attendance"
on public.attendance for insert to anon, authenticated with check (true);

drop policy if exists "Public kiosk can update attendance" on public.attendance;
create policy "Public kiosk can update attendance"
on public.attendance for update to anon, authenticated using (true) with check (true);

drop policy if exists "Public kiosk can read matches" on public.matches;
create policy "Public kiosk can read matches"
on public.matches for select to anon, authenticated using (true);

drop policy if exists "Public kiosk can create matches" on public.matches;
create policy "Public kiosk can create matches"
on public.matches for insert to anon, authenticated with check (true);

drop policy if exists "Public kiosk can update matches" on public.matches;
create policy "Public kiosk can update matches"
on public.matches for update to anon, authenticated using (true) with check (true);

-- 이미 퍼블리케이션에 포함된 경우를 대비해 중복 추가 오류를 무시한다.
do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.attendance;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.matches;
exception when duplicate_object then null;
end $$;
